### PR TITLE
Value::Unsigned

### PR DESCRIPTION
**Pull request by kirillt**
Tiny PR adding unsigned integers

### CODE REVIEW

**Comment by driftluo** [comment]
https://docs.influxdata.com/influxdb/v1.8/write_protocols/line_protocol_reference/#data-types
There is no uint type in the reference

**Comment by kirillt** [comment]
@driftluo indeed, I looked at v2.0 reference, sorry!

**Comment by driftluo** [comment]
There are quite a few API changes and protocol changes in 2.0, and it is still unstable, and I haven’t paid much attention to its progress recently :p

**Comment by kirillt** [comment]
@driftluo official Docker image is 1.8.0 so I think there is no much sense to rush with adopting 2.0 :)

**Pull request closed without merging**
